# Copyright 2026 RooflineAI GmbH
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@llvm-project//mlir:tblgen.bzl", "gentbl_cc_library", "td_library")
load("@iree_hexagon_plugins//build_tools/bazel:defs.bzl", "hexagon_mlir_overlay_library")

package(default_visibility = ["//visibility:public"])

td_library(
    name = "CopyOpInterfaceTdFiles",
    srcs = ["CopyOpInterface.td"],
    includes = ["/qcom_hexagon_backend/include"],
    deps = ["@llvm-project//mlir:OpBaseTdFiles"],
)

gentbl_cc_library(
    name = "CopyOpInterfaceIncGen",
    strip_include_prefix = "/qcom_hexagon_backend/include",
    tbl_outs = {
        "CopyOpInterface.h.inc": ["-gen-op-interface-decls"],
        "CopyOpInterface.cpp.inc": ["-gen-op-interface-defs"],
    },
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "CopyOpInterface.td",
    deps = [":CopyOpInterfaceTdFiles"],
)

filegroup(
    name = "CopyOpInterfaceHeader",
    srcs = ["CopyOpInterface.h"],
)

hexagon_mlir_overlay_library(
    name = "CopyOpInterface",
    srcs = ["CopyOpInterface.cpp"],
    hdrs = [":CopyOpInterfaceHeader"],
    includes = ["../.."],
    deps = [
        ":CopyOpInterfaceIncGen",
    ],
    hdr_deps = [
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:IR",
    ],
)
