# Copyright 2026 RooflineAI GmbH
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@iree_hexagon_plugins//build_tools/bazel:defs.bzl", "hexagon_mlir_overlay_library")

package(default_visibility = ["//visibility:public"])

hexagon_mlir_overlay_library(
    name = "HexagonMemToLLVM",
    srcs = [
        "HexagonMemExternalFnNames.cpp",
        "HexagonMemToLLVMPass.cpp",
    ],
    copts = [
        # hexagon-mlir still uses deprecated IRRewriter::create APIs.
        "-Wno-deprecated-declarations",
    ],
    deps = [
        "@hexagon-mlir//qcom_hexagon_backend/include/hexagon:ConversionHeadersLib",
        "@hexagon-mlir//qcom_hexagon_backend/include/hexagon:HexagonMemHeadersLib",
        "@hexagon-mlir//qcom_hexagon_backend/lib/Common:HexagonCommon",
        "@hexagon-mlir//qcom_hexagon_backend/lib/Dialect/HexagonMem/IR:HexagonMem",
    ],
    hdr_deps = [
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:Analysis",
        "@llvm-project//mlir:ArithDialect",
        "@llvm-project//mlir:ConversionPasses",
        "@llvm-project//mlir:ConvertToLLVM",
        "@llvm-project//mlir:DialectUtils",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:LLVMCommonConversion",
        "@llvm-project//mlir:LLVMDialect",
        "@llvm-project//mlir:MemRefDialect",
        "@llvm-project//mlir:MemRefTransforms",
        "@llvm-project//mlir:Pass",
        "@llvm-project//mlir:Transforms",
    ],
)
