load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@roof_mlir//:build_tools/bazel/platform_aliases.bzl", "hexagon_platform_alias")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_import.bzl", "cc_import")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

cc_import(
    name = "qurt_lib",
    static_library = "@hexagon_sdk//:rtos/qurt/computev68/lib/libqurt.a",
)

cc_binary(
    name = "hexagon_dsp_skel",
    srcs = [
        "align.h",
        "buffer.c",
        "command_buffer.c",
        "device.c",
        "executable.c",
        "executable.h",
        "import_provider.c",
        "import_provider.h",
        "power_mode.c",
        "power_mode.h",
        "//plugins/runtime/hexagon/interface:hexagon_dsp_skel_c",
    ],
    copts = [
        "-Wswitch-enum",
    ],
    defines = select({
        "@iree//runtime/src/iree/base/tracing:_tracy_enable": [
            "IREE_HAL_HEXAGON_ENABLE_PROFILER",
        ],
        "//conditions:default": [],
    }),
    includes = ["../.."],
    linkshared = True,
    target_compatible_with = [
        "@patio_cellar_hexagon//constraints:os_qurt",
        "@patio_cellar_hexagon//constraints:cpu_hexagon",
    ],
    deps = [
        ":qurt_lib",
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
        "//plugins/runtime/hexagon/dsp/pmu:hexagon_pmu_helpers",
        "//plugins/runtime/hexagon/dsp/rt:hexagon_rt_library",
        "//plugins/runtime/hexagon/interface:hexagon_dsp_skel_hdr_lib",
        "@hexagon-mlir//qcom_hexagon_backend/bin/runtime:runtime_lib",
        "@iree//runtime/src/iree/hal/local:executable_library",
    ],
)

hexagon_platform_alias(
    name = "hexagon_dsp_skel_cross",
    actual = "hexagon_dsp_skel",
)

copy_file(
    name = "hexagon_dsp_skel_out",
    src = ":hexagon_dsp_skel_cross",
    out = "lib/hexagon/libhexagon_dsp_skel.so",
    target_compatible_with = select({
        "@patio_cellar_hexagon//plugins/runtime/hexagon:hexagon_runtime_enabled": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
