load("@aspect_bazel_lib//lib:copy_file.bzl", "copy_file")
load("@roof_mlir//:build_tools/bazel/hexagon_platform_alias.bzl", "hexagon_platform_alias")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

cc_binary(
    name = "hexagon_dsp_skel",
    srcs = [
        "buffer.c",
        "command_buffer.c",
        "device.c",
        "executable.c",
        "executable.h",
        "//hexagon/interface:hexagon_dsp_skel_c",
    ],
    linkshared = True,
    target_compatible_with = [
        "@//constraints:os_qurt",
        "@//constraints:cpu_hexagon",
    ],
    deps = [
        "//hexagon/arm_dsp:hexagon_arm_dsp",
        "//hexagon/interface:hexagon_dsp_skel_hdr_lib",
        "@iree//runtime/src/iree/hal/local:executable_library",
    ],
)

hexagon_platform_alias(
    name = "hexagon_dsp_skel_cross",
    actual = "hexagon_dsp_skel",
)

copy_file(
    name = "hexagon_dsp_skel_out",
    src = ":hexagon_dsp_skel_cross",
    out = "lib/hexagon/libhexagon_dsp_skel.so",
    target_compatible_with = select({
        "@patio_runtime//hexagon:hexagon_runtime_enabled": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
)
