# Copyright 2025 RooflineAI GmbH
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@aspect_rules_py//py:defs.bzl", "py_test")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

py_test(
    name = "test_dsp_runtime_exports",
    srcs = [
        "conftest.py",
        "test_dsp_runtime_exports.py",
    ],
    args = [
        "--runtime-so",
        "$(location //plugins/runtime/hexagon/dsp:hexagon_dsp_skel_cross)",
    ],
    data = ["//plugins/runtime/hexagon/dsp:hexagon_dsp_skel_cross"],
    deps = [
        "@pypi//pyelftools",
        "@pypi//pytest",
    ],
)

cc_library(
    name = "serialize_test_utils",
    srcs = ["serialize_test_utils.cc"],
    hdrs = ["serialize_test_utils.h"],
    deps = [
        "//plugins/runtime/hexagon/serialize:serialize_plugin",
        "@iree//runtime/src/iree/base",
        "@iree//runtime/src/iree/hal",
    ],
)

cc_test(
    name = "bindings_serialize_test",
    srcs = [
        "bindings_serialize_test.cc",
    ],
    deps = [
        ":serialize_test_utils",
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
        "//plugins/runtime/hexagon/serialize:serialize_plugin",
        "@iree//runtime/src/iree/testing:gtest",
        "@iree//runtime/src/iree/testing:gtest_main",
    ],
)

cc_test(
    name = "cmd_barrier_serialize_test",
    srcs = ["cmd_barrier_serialize_test.cc"],
    deps = [
        ":serialize_test_utils",
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
        "//plugins/runtime/hexagon/serialize:serialize_plugin",
        "@iree//runtime/src/iree/testing:gtest",
        "@iree//runtime/src/iree/testing:gtest_main",
    ],
)

cc_test(
    name = "cmd_copy_serialize_test",
    srcs = ["cmd_copy_serialize_test.cc"],
    deps = [
        ":serialize_test_utils",
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
        "//plugins/runtime/hexagon/serialize:serialize_plugin",
        "@iree//runtime/src/iree/testing:gtest",
        "@iree//runtime/src/iree/testing:gtest_main",
    ],
)

cc_test(
    name = "cmd_dispatch_serialize_test",
    srcs = ["cmd_dispatch_serialize_test.cc"],
    deps = [
        ":serialize_test_utils",
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
        "//plugins/runtime/hexagon/serialize:serialize_plugin",
        "@iree//runtime/src/iree/testing:gtest",
        "@iree//runtime/src/iree/testing:gtest_main",
    ],
)

cc_test(
    name = "cmd_fill_serialize_test",
    srcs = ["cmd_fill_serialize_test.cc"],
    deps = [
        ":serialize_test_utils",
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
        "//plugins/runtime/hexagon/serialize:serialize_plugin",
        "@iree//runtime/src/iree/testing:gtest",
        "@iree//runtime/src/iree/testing:gtest_main",
    ],
)

cc_test(
    name = "command_buffer_serialize_test",
    srcs = [
        "command_buffer_serialize_test.cc",
    ],
    deps = [
        ":serialize_test_utils",
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
        "//plugins/runtime/hexagon/serialize:serialize_plugin",
        "@iree//runtime/src/iree/testing:gtest",
        "@iree//runtime/src/iree/testing:gtest_main",
    ],
)
