load("//build_tools/bazel:defs.bzl", "hexagon_mlir_overlay_library")

package(default_visibility = ["//visibility:public"])

hexagon_mlir_overlay_library(
    name = "HexagonMem",
    srcs = [
        "HexagonMemAttrs.cpp",
        "HexagonMemDialect.cpp",
        "HexagonMemOps.cpp",
        "HexagonMemTypes.cpp",
    ],
    deps = [
        "@hexagon-mlir//qcom_hexagon_backend/include/hexagon:HexagonMemHeadersLib",
        "@hexagon-mlir//qcom_hexagon_backend/include/hexagon:HexagonMemTableGen",
        "@hexagon-mlir//qcom_hexagon_backend/include/mlir/Interfaces:CopyOpInterface",
        "@hexagon-mlir//qcom_hexagon_backend/lib/Common:HexagonCommon",
    ],
    hdr_deps = [
        "@llvm-project//mlir:BufferizationDialect",
        "@llvm-project//mlir:BytecodeOpInterface",
        "@llvm-project//mlir:DestinationStyleOpInterface",
        "@llvm-project//mlir:DialectUtils",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:LinalgDialect",
        "@llvm-project//mlir:LinalgUtils",
        "@llvm-project//mlir:MemRefDialect",
        "@llvm-project//mlir:SideEffectInterfaces",
        "@llvm-project//mlir:Support",
    ],
)
