# Copyright 2025 RooflineAI GmbH

load("//build_tools/bazel:hexagon_interface.bzl", "hexagon_interface")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

hexagon_interface(
    name = "hexagon_dsp_interface",
    input_idl = "hexagon_dsp.idl",
    interface_name = "hexagon_dsp",
    output_dir = "hexagon_dsp",
)

filegroup(
    name = "hexagon_dsp_header",
    srcs = [":hexagon_dsp_interface"],
    output_group = "header",
)

filegroup(
    name = "hexagon_dsp_stub_c",
    srcs = [":hexagon_dsp_interface"],
    output_group = "stub",
)

filegroup(
    name = "hexagon_dsp_skel_c",
    srcs = [":hexagon_dsp_interface"],
    output_group = "skel",
)

cc_library(
    name = "hexagon_dsp_stub_lib",
    srcs = [":hexagon_dsp_stub_c"],
    hdrs = [":hexagon_dsp_header"],
    includes = ["hexagon_dsp"],
    deps = [
        "@hexagon_sdk//:cdsprpc_android_aarch64",
    ],
)

cc_library(
    name = "hexagon_dsp_skel_hdr_lib",
    hdrs = [":hexagon_dsp_header"],
    includes = ["hexagon_dsp"],
)
