# Copyright 2026 RooflineAI GmbH
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@aspect_rules_py//py:defs.bzl", "py_test")

package(
    default_visibility = ["//visibility:public"],
    licenses = [],
)

py_test(
    name = "model_tree",
    srcs = glob(
        ["**/*.py"],
        exclude = ["models/**"],
    ),
    args = ["$(rootpath test_model_tree.py)"],
    data = glob([
        "models/*/*/model.yaml",
        "models/*/*/model.py",
    ]) + ["test_model_tree.py"],
    main = "run_pytest.py",
    deps = [
        "@pypi//numpy",
        "@pypi//pytest",
        "@pypi//pyyaml",
    ],
)
