# Copyright 2025 RooflineAI GmbH

load("//build_tools/bazel:defs.bzl", "hexagon_plugin_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

# serialize_plugin uses header-only IREE deps, which provide
# types at compile time without pulling in any IREE object code.
# Note that this target is used in the unit tests and therefore
# they will only pass when no call to IREE happens in them.

hexagon_plugin_library(
    name = "serialize_plugin",
    srcs = [
        "bindings_serialize.c",
        "cmd_barrier_serialize.c",
        "cmd_copy_serialize.c",
        "cmd_dispatch_serialize.c",
        "cmd_fill_serialize.c",
        "command_buffer_serialize.c",
    ],
    hdrs = [
        "bindings_serialize.h",
        "cmd_barrier_serialize.h",
        "cmd_copy_serialize.h",
        "cmd_dispatch_serialize.h",
        "cmd_fill_serialize.h",
        "command_buffer_serialize.h",
        "command_buffer_types.h",
        "rpc_types.h",
        "serialize.h",
    ],
    copts = [
        "-Wswitch-enum",
    ],
    hdr_deps = [
        "@iree//runtime/src/iree/base",
        "@iree//runtime/src/iree/hal",
        "@iree//runtime/src/iree/hal/utils:resource_set",
    ],
    includes = [
        ".",
        "../..",
    ],
    deps = [
        "//plugins/runtime/hexagon/arm_dsp:hexagon_arm_dsp",
    ],
)
