# Copyright 2025 RooflineAI GmbH

load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

cc_library(
    name = "serialize",
    srcs = [
        "bindings_serialize.c",
        "command_buffer_serialize.c",
    ],
    hdrs = [
        "bindings_serialize.h",
        "command_buffer_serialize.h",
        "command_buffer_types.h",
        "rpc_types.h",
        "serialize.h",
    ],
    copts = [
        "-Wswitch-enum",
    ],
    includes = [
        ".",
    ],
    deps = [
        "//hexagon/arm_dsp:hexagon_arm_dsp",
        "@iree//runtime/src/iree/base",
        "@iree//runtime/src/iree/hal",
        "@iree//runtime/src/iree/hal/utils:resource_set",
    ],
)
