# Copyright 2025 RooflineAI GmbH

load("@iree//build_tools/bazel:build_defs.oss.bzl", "iree_runtime_cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

config_setting(
    name = "hexagon_runtime_enabled",
    constraint_values = [
        "@platforms//cpu:aarch64",
        "@platforms//os:android",
    ],
)

iree_runtime_cc_library(
    name = "hexagon",
    srcs = [
        "allocator.c",
        "allocator.h",
        "buffer.c",
        "buffer.h",
        "channel.c",
        "channel.h",
        "command_buffer.c",
        "command_buffer.h",
        "device.c",
        "device.h",
        "driver.c",
        "driver.h",
        "event.c",
        "event.h",
        "executable.c",
        "executable.h",
        "executable_cache.c",
        "executable_cache.h",
        "rpc_types.h",
        "semaphore.c",
        "semaphore.h",
        "utils.c",
        "utils.h",
    ],
    hdrs = [
        "api.h",
    ],
    data = [
        "//hexagon/dsp:hexagon_dsp_skel_out",
    ],
    deps = [
        "//hexagon/interface:hexagon_dsp_stub_lib",
        "@hexagon_sdk//:cdsprpc_android_aarch64",
        "@iree//runtime/src/iree/base",
        "@iree//runtime/src/iree/base/internal",
        "@iree//runtime/src/iree/hal",
        "@iree//runtime/src/iree/hal/utils:file_transfer",
        "@iree//runtime/src/iree/hal/utils:files",
        "@iree//runtime/src/iree/hal/utils:queue_emulation",
        "@iree//runtime/src/iree/hal/utils:queue_host_call_emulation",
        "@iree//runtime/src/iree/hal/utils:semaphore_base",
    ],
)
