// Copyright 2025 RooflineAI GmbH

// This file checks statically that the type aliases defined in rpc_types
// match the actual types defined by the hexagon_dsp.h file generated by the
// Hexagon SDK.
// This file is just compiled on aarch64 where the generated hexagon_dsp.h is
// available.

#include "rpc_types.h"

#include "hexagon_dsp.h"

#define ASSERT_T_EQ(a, b)                                                      \
  _Static_assert(__builtin_types_compatible_p(a, b),                           \
                 "DSP RCP type mismatch, fix type in rpc_types.h")

ASSERT_T_EQ(remote_handle64, rpc_session_handle_t);

ASSERT_T_EQ(int64, rpc_executable_handle_t);

ASSERT_T_EQ(int64, rpc_command_buffer_handle_t);
