# Copyright 2025 RooflineAI GmbH
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = [],
)

cc_library(
    name = "hexagon_pmu_events",
    srcs = [],
    hdrs = [
        "hexagon_pmu_events_ids.h",
        "hexagon_pmu_events_table.inc",
    ],
    strip_include_prefix = "/plugins/runtime",
)
