# Copyright 2026 RooflineAI GmbH
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

package(default_visibility = ["//visibility:public"])

# The platform package does not provide constraint definitions for Hexagon CPU
# and its QURT OS, so define those here.

constraint_value(
    name = "cpu_hexagon",
    constraint_setting = "@platforms//cpu:cpu",
)

constraint_value(
    name = "os_qurt",
    constraint_setting = "@platforms//os:os",
)
