load("@patio_cellar_hexagon//build_tools/bazel:defs.bzl", "hexagon_mlir_overlay_library")

package(default_visibility = ["//visibility:public"])

hexagon_mlir_overlay_library(
    name = "HexagonCommon",
    srcs = [
        "Common.cpp",
        "DMATransferUtil.cpp",
    ],
    copts = [
        # hexagon-mlir upstream still uses deprecated IRRewriter::create APIs.
        "-Wno-deprecated-declarations",
    ],
    deps = [
        "@hexagon-mlir//qcom_hexagon_backend/include/hexagon:ConversionHeadersLib",
        "@hexagon-mlir//qcom_hexagon_backend/include/hexagon:HexagonCommonHeaders",
        "@hexagon-mlir//qcom_hexagon_backend/include/hexagon:HexagonMemHeadersLib",
    ],
    hdr_deps = [
        "@llvm-project//mlir:ArithDialect",
        "@llvm-project//mlir:FuncDialect",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:LLVMCommonConversion",
        "@llvm-project//mlir:LLVMDialect",
        "@llvm-project//mlir:LinalgTransforms",
        "@llvm-project//mlir:MemRefUtils",
        "@llvm-project//mlir:Pass",
    ],
)
